@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2Njc5NDMyNjV9.A_zVxqoSy2MBEJpYS9ZfXCDnxSElIUfkZt0QBjv5nuU
@admin = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Njc5NDM2NDZ9.S4fsoOWp_Wh1xqm6BVivH5_REfFa9_v2jexoaCxxpWM

### Openings Index Action
GET http://localhost:3000/openings.json

### Openings Show Action
GET http://localhost:3000/openings/1.json

### Openings Create Action
POST http://localhost:3000/openings.json
Authorization: Bearer {{admin}}
Content-Type: application/json

{
  "name": "test opening",
  "image_url": "test image",
  "description": "test description",
  "difficulty": "test",
  "variation": ""
}

### Opening Update Action
PATCH http://localhost:3000/openings/6.json
Content-Type: application/json

{
  "variation": "test patch"
}

### Opening Destroy Action
DELETE http://localhost:3000/openings/6.json
Authorization: Bearer {{admin}}

### Studies Index Action
GET http://localhost:3000/studies.json

### Studies Show Action
GET http://localhost:3000/studies/1.json

### Studies Create Action
POST http://localhost:3000/studies.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "opening_id": 3,
  "notes": "yes of course",
  "public": false
}

### Studies Update Action
PATCH http://localhost:3000/studies/4.json
Content-Type: application/json

{
  "user_id": 3,
  "opening_id": 1,
  "notes": "well that sucks"
}

### Studies Destroy Action
DELETE http://localhost:3000/studies/4.json


### Users Create Action
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "email": "chessfan@test.com"
}

### Session Create Action
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "capablanca@email.com",
  "password": "password"
}


### Resources Create Action
POST http://localhost:3000/resources.json
Authorization: Bearer {{admin}}
Content-Type: application/json

{
  "opening_id": 2,
  "link": "test",
  "resource_type": "Online"
}

### Resources Update Action
PATCH http://localhost:3000/resources/2.json
Authorization: Bearer {{admin}}
Content-Type: application/json

{
  "opening_id": 3,
  "link": 2,
  "resource_type": "Online"
}

### Resources Delete Action
DELETE http://localhost:3000/resources/2.json
Authorization: Bearer {{admin}}
